analyze_damage_image:
  model: "accounts/fireworks/models/qwen2p5-vl-32b-instruct"
  temperature: 0.0

incident_response:
  model: "accounts/fireworks/models/llama4-scout-instruct-basic"
  temperature: 0.0

report_generation:
  model: "accounts/fireworks/models/deepseek-v3-0324"
  temperature: 0.0
