vision_damage_analysis:
  simple: |
    Describe the car damage you see in this image.

  intermediate: |
    Analyze this car damage image and provide:

    1. What type of damage do you see?
    2. How severe is the damage?
    3. Which parts of the car are affected?
    4. Estimate if this is minor, moderate, or major damage.

    Please be specific and detailed in your response.

  advanced: |
    You are an expert automotive claims adjuster analyzing vehicle damage. Examine this image carefully and provide a comprehensive damage assessment.

    **SEVERITY DEFINITIONS:**
    - **minor**: Cosmetic damage, scratches, small dents < 2 inches
    - **moderate**: Noticeable damage affecting function, dents 2-6 inches, cracked lights
    - **major**: Structural damage, large dents > 6 inches, safety systems affected

    **LOCATION DEFINITIONS:**
    - **front-left**: Driver side front (hood, front bumper, headlight, driver door front portion)
    - **front-right**: Passenger side front (hood, front bumper, headlight, passenger door front portion)
    - **back-left**: Driver side rear (trunk, rear bumper, taillight, driver door rear portion)
    - **back-right**: Passenger side rear (trunk, rear bumper, taillight, passenger door rear portion)

    **INSTRUCTIONS:**
    1. Examine the entire visible vehicle surface
    2. Identify the primary damage location using the quadrant system
    3. Assess severity based on size, depth, and functional impact
    4. Provide a clear, detailed description of what you observe
    5. If damage spans multiple quadrants, choose the most severely affected area
    6. Be conservative in estimates - when uncertain, classify as higher severity

    Focus on accuracy and consistency. This analysis will be used for insurance claim processing.
